import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen py-16 flex flex-1 flex-col justify-center items-center">
        <h1 className="leading-tight px-6 text-6xl font-bold">
          Welcome to{' '}
          <a href="https://nextjs.org" className="hover:text-blue-500">
            Next.js
          </a>
        </h1>
        <p className="my-4">
          Get started by editing
          <code className="mx-2 py-2 px-2 bg-zinc-100 rounded-md font-mono">
            pages/index.tsx
          </code>
        </p>
        <div className="max-w-screen-md flex flex-wrap justify-center items-center">
          <a
            href="https://nextjs.org/docs"
            className="max-w-xs m-4 p-6 text-left border rounded-xl hover:text-blue-500 hover:border-blue-500"
          >
            <h2 className="mb-2 text-2xl font-bold">Documentation</h2>
            <p className="text-sm">
              Find in-depth information about Next.js features and API.
            </p>
          </a>
          <a
            href="https://nextjs.org/learn"
            className="max-w-xs m-4 p-6 text-left border rounded-xl hover:text-blue-500 hover:border-blue-500"
          >
            <h2 className="mb-2 text-2xl font-bold">Learn</h2>
            <p className="text-sm">
              Learn about Next.js in an interactive course with quizzes!
            </p>
          </a>
          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className="max-w-xs m-4 p-6 text-left border rounded-xl hover:text-blue-500 hover:border-blue-500"
          >
            <h2 className="mb-2 text-2xl font-bold">Examples</h2>
            <p className="text-sm">
              Discover and deploy boilerplate example Next.js projects.
            </p>
          </a>
          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className="max-w-xs m-4 p-6 text-left border rounded-xl hover:text-blue-500 hover:border-blue-500"
          >
            <h2 className="mb-2 text-2xl font-bold">Deploy</h2>
            <p className="text-sm">
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>
      <footer className="py-4 flex flex-1 border-t border-solid justify-center items-center">
        <div className="flex flex-grow justify-center items-center text-sm">
          Powered by{' '}
          <a
            href="https://vercel.com"
            target="_blank"
            rel="noopener noreferrer"
            className="ml-1 hover:text-blue-600"
          >
            Vercel
          </a>
        </div>
      </footer>
    </>
  );
};

export default Home;
